version: "3.3"
services:
  nginx:
    image: nginx:1.25.2-alpine
    ports:
      - 80:80
    volumes:
      - ./:/etc/nginx/templates 
    extra_hosts:
      - "host.docker.internal:host-gateway"

#trigger