name: Manual rollback deploy for devel

on:
  workflow_dispatch:
    inputs:
      client_backend:
        description: 'Choice client or backend'
        required: true
        default: 'client'
        type: choice
        options:
          - client
          - backend
      tag_version:
        description: 'Enter the service version to deploy'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Display variables
        run: |
          echo "Environment to rollback: ${{ github.event.inputs.client_backend }}"
          echo "Tag to rollback: ${{ github.event.inputs.tag_version }}"

###############################################################################
# DEPLOY client
###############################################################################

  # TODO : Replace DEV_ environment by PROD_
  deploy_client:
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.client_backend == 'client' }}
    env:
      DEPLOYMENT_SERVER_HOST: ${{ vars.DEV_SERVER_HOST }}
      APP_ENDPOINT: http://${{ vars.DEV_SERVER_HOST }}
      SERVICE: client
      APP_PORT: 80
      HOST_PORT: 8000
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build development environment in client server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ vars.DEV_SERVER_HOST }}
          username: admin
          key: ${{ secrets.DEV_SSH_PRIVATE_KEY }}
          script: |
            echo "Remove old images"
            sudo docker image prune -af --filter "until=$((15*24))h"
            echo "Remove old images root"
            docker image prune -af --filter "until=$((15*24))h"

            export repo=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
            export IMAGE_NAME=ghcr.io/${repo}/${{ env.SERVICE }}
            export TAG=${{ github.event.inputs.tag_version }}

            mkdir -p ~/${{ env.SERVICE }}
            cd ${{ env.SERVICE }}
            echo COMPOSE_PROJECT_NAME=${{ env.SERVICE }} > .env
            echo DC_IMAGE_NAME=$IMAGE_NAME >> .env
            echo DC_IMAGE_TAG=$TAG >> .env
            echo DC_APP_PORT=${{ env.APP_PORT }} >> .env
            echo DC_HOST_PORT=${{ env.HOST_PORT }} >> .env

            cat ./.env

      - name: copy file via scp
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ vars.DEV_SERVER_HOST }}
          username: admin
          key: ${{ secrets.DEV_SSH_PRIVATE_KEY }}
          source: "./docker-compose.yaml"
          target: "${{ env.SERVICE }}/"

      - name: Run Dev container
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ vars.DEV_SERVER_HOST }}
          username: admin
          key: ${{ secrets.DEV_SSH_PRIVATE_KEY }}
          script: |
            cd ${{ env.SERVICE }}
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io --username ${{ github.repository_owner }} --password-stdin
            docker-compose down
            docker-compose up -d


###############################################################################
# DEPLOY backend
###############################################################################

  # TODO : Replace DEV_ environment by PROD_
  deploy_backend_dev:
    if: ${{ github.event.inputs.client_backend == 'backend' }}
    runs-on: ubuntu-latest
    env:
      DEPLOYMENT_SERVER_HOST: ${{ vars.DEV_SERVER_HOST }}
      APP_ENDPOINT: http://${{ vars.DEV_SERVER_HOST }}
      SERVICE: backend
      APP_PORT: 5000
      HOST_PORT: 5000
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build development environment in backend server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ vars.DEV_SERVER_HOST }}
          username: admin
          key: ${{ secrets.DEV_SSH_PRIVATE_KEY }}
          script: |
            echo "Remove old images"
            sudo docker image prune -af --filter "until=$((15*24))h"
            echo "Remove old images root"
            docker image prune -af --filter "until=$((15*24))h"

            export repo=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
            export IMAGE_NAME=ghcr.io/${repo}/${{ env.SERVICE }}
            export TAG=${{ github.event.inputs.tag_version }}

            mkdir -p ~/${{ env.SERVICE }}
            cd ${{ env.SERVICE }}
            echo COMPOSE_PROJECT_NAME=${{ env.SERVICE }} > .env
            echo DC_IMAGE_NAME=$IMAGE_NAME >> .env
            echo DC_IMAGE_TAG=$TAG >> .env
            echo DC_APP_PORT=${{ env.APP_PORT }} >> .env
            echo DC_HOST_PORT=${{ env.HOST_PORT }} >> .env
            echo "PG_PASSWORD=${{ secrets.DEV_PG_PASSWORD}}" >> .env
            echo PG_USER=${{ vars.DEV_PG_USER }} >> .env
            echo PG_HOST=${{ vars.DEV_PG_HOST }} >> .env
            echo PG_DATABASE=${{ vars.DEV_PG_DATABASE }} >> .env

            cat ./.env

      - name: copy file via scp
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ vars.DEV_SERVER_HOST }}
          username: admin
          key: ${{ secrets.DEV_SSH_PRIVATE_KEY }}
          source: "./docker-compose.yaml"
          target: "${{ env.SERVICE }}/"

      - name: Run Dev container
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ vars.DEV_SERVER_HOST }}
          username: admin
          key: ${{ secrets.DEV_SSH_PRIVATE_KEY }}
          script: |
            cd ${{ env.SERVICE }}
            echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io --username ${{ github.repository_owner }} --password-stdin
            docker-compose down
            docker-compose up -d
